// <auto-generated />
using System;
using HCS.Security.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCS.Security.Migrations
{
    [DbContext(typeof(HCSSecurityDBContext))]
    [Migration("20230319010404_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HCS.Security.Models.Base.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginFailedAttemptsCount")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaltKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1c93a83-9c7f-4320-b96b-133ef401990d"),
                            CreatedDate = new DateTime(2023, 3, 19, 1, 4, 3, 662, DateTimeKind.Utc).AddTicks(2114),
                            Email = "sbhowmikcse08@gmail.com",
                            FullName = "Sreemonta Bhowmik",
                            LastLoginAttemptAt = new DateTime(2023, 3, 19, 5, 4, 3, 662, DateTimeKind.Local).AddTicks(2065),
                            LoginFailedAttemptsCount = 0,
                            Password = "$2b$10$dqPNaHnCGjUcvxXHTRXmDeNwNRQ0YI8kT9376noZw8i8tDj8KKoEa",
                            SaltKey = "$2b$10$dqPNaHnCGjUcvxXHTRXmDe",
                            UpdatedDate = new DateTime(2023, 3, 19, 1, 4, 3, 662, DateTimeKind.Utc).AddTicks(2115),
                            UserName = "sree",
                            UserRole = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
